# Generated by Django 3.0.2 on 2020-02-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
